module.exports = {
    apps: [
        {
            name: 'nova-tag-TAG1',
            script: './dist/server.js',
            args: 'TAG1',
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            max_memory_restart: '500M',
            env: {
                NODE_ENV: 'production',
                TAG_ID: 'TAG1',
            },
            error_file: './logs/pm2-error-TAG1.log',
            out_file: './logs/pm2-out-TAG1.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: false,
            min_uptime: '10s',
            max_restarts: 10,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
        },
        {
            name: 'nova-tag-TAG2',
            script: './dist/server.js',
            args: 'TAG2',
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            max_memory_restart: '500M',
            env: {
                NODE_ENV: 'production',
                TAG_ID: 'TAG2',
            },
            error_file: './logs/pm2-error-TAG2.log',
            out_file: './logs/pm2-out-TAG2.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: false,
            min_uptime: '10s',
            max_restarts: 10,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
        },
    ],
};
